/*
 * STYLELINT Configuration file
 */
module.exports = {
  extends: [
    "stylelint-config-standard",
    "stylelint-config-standard-scss"
  ],
  plugins: ["stylelint-order"],
	rules: {
    "declaration-empty-line-before": null,
		"order/order": [
			[
				"dollar-variables",
				"custom-properties",
				"at-rules",
				"declarations",
				{
					"type": "at-rule",
					"name": "supports"
				},
				{
					"type": "at-rule",
					"name": "media"
				},
				"rules"
			],
			{ "severity": "warning" }
		],
		"order/properties-order": [
      [
        /* position */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "positionGroup",
          "order": null,
          "properties": [
            "bottom",
            "clear",
            "inset",
            "inset-block",
            "inset-block-end",
            "inset-block-start",
            "inset-inline",
            "inset-inline-end",
            "inset-inline-start",
            "left",
            "",
            "",
            "",
            "",
          ]
        },
        /* display */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "displayGroup",
          "order": null,
          "properties": [
            "display",
            "flex",
            "flex-basis",
            "flex-direction",
            "flex-flow",
            "flex-grow",
            "flex-shrink",
            "flex-wrap",
            "float",
            "grid",
            "grid-area",
            "grid-auto-columns",
            "grid-auto-flow",
            "grid-auto-rows",
            "grid-column",
            "grid-column-end",
            "grid-column-start",
            "grid-row",
            "grid-row-end",
            "grid-row-start",
            "grid-template",
            "grid-template-areas",
            "grid-template-columns",
            "grid-template-rows",
            "justify-content",
            "justify-items",
            "justify-self",
            "justify-tracks",
            "masonry-auto-flow",
            "",
          ]
        },
        /* box */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "boxGroup",
          "order": null,
          "properties": [
            "aspect-ratio",
            "align-content",
            "align-items",
            "align-self",
            "align-tracks",
            "border",
            "border-block",
            "border-block-color",
            "border-block-end",
            "border-block-end-color",
            "border-block-end-style",
            "border-block-end-width",
            "border-block-start",
            "border-block-start-color",
            "border-block-start-style",
            "border-block-start-width",
            "border-block-style",
            "border-block-width",
            "border-bottom",
            "border-bottom-color",
            "border-bottom-left-radius",
            "border-bottom-right-radius",
            "border-bottom-style",
            "border-bottom-width",
            "border-collapse",
            "border-color",
            "border-end-end-radius",
            "border-end-start-radius",
            "border-image",
            "border-image-outset",
            "border-image-repeat",
            "border-image-slice",
            "border-image-source",
            "border-image-width",
            "border-inline",
            "border-inline-color",
            "border-inline-end",
            "border-inline-end-color",
            "border-inline-end-style",
            "border-inline-end-width",
            "border-inline-start",
            "border-inline-start-color",
            "border-inline-start-style",
            "border-inline-start-width",
            "border-inline-style",
            "border-inline-width",
            "border-left",
            "border-left-color",
            "border-left-style",
            "border-left-width",
            "border-radius",
            "border-right",
            "border-right-color",
            "border-right-style",
            "border-right-width",
            "border-spacing",
            "border-start-end-radius",
            "border-start-start-radius",
            "border-style",
            "border-top",
            "border-top-color",
            "border-top-left-radius",
            "border-top-right-radius",
            "border-top-style",
            "border-top-width",
            "border-width",
            "box-sizing",                        
            "break-after",                        
            "break-before",                        
            "break-inside",                        
            "height",                        
            "inline-size",     
            "list-style",
            "list-style-image",
            "list-style-position",
            "list-style-type",
            "margin",
            "margin-block",
            "margin-block-end",
            "margin-block-start",
            "margin-bottom",
            "margin-inline",
            "margin-inline-end",
            "margin-inline-start",
            "margin-left",
            "margin-right",
            "margin-top",
            "margin-trim",
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
            "",                        
          ]
        },
        /* table */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "tableGroup",
          "order": null,
          "properties": [
            "caption-side",
            "empty-cells",
            "",
            "",
            "",
            "",
            "",
            "",
          ]
        },
        /* typography */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "typographyGroup",
          "order": null,
          "properties": [
            "all",
            "direction",
            "font",
            "font-family",
            "font-feature-settings",
            "font-kerning",
            "font-language-override",
            "font-optical-sizing",
            "font-palette",
            "font-size",
            "font-size-adjust",
            "font-smooth",
            "font-stretch",
            "font-style",
            "font-synthesis",
            "font-synthesis-small-caps",
            "font-synthesis-style",
            "font-synthesis-weight",
            "font-variant",
            "font-variant-alternates",
            "font-variant-caps",
            "font-variant-east-asian",
            "font-variant-emoji",
            "font-variant-ligatures",
            "font-variant-numeric",
            "font-variant-position",
            "font-weight",
            "hanging-punctuation",
            "hyphenate-character",
            "hyphenate-limit-chars",
            "hyphens",
            "initial-letter",
            "initial-letter-align",
            "letter-spacing",
            "line-breack",
            "line-clamp",
            "line-grid",
            "line-height",
            "line-height-step",
            "",
            "",
          ]
        },
        /* forms */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "miscGroup",
          "order": null,
          "properties": [
            "accent-color",
            "",
            "",
            "",
            "",
            "",
            "",
          ]
        },
        /* animation */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "animationGroup",
          "order": null,
          "properties": [
            "animation",
            "animation-composition",
            "animation-delay",
            "animation-direction",
            "animation-duration",
            "animation-fill-mode",
            "animation-iteration-count",
            "animation-name",
            "animation-play-state",
            "animation-range",
            "animation-range-end",
            "animation-range-start",
            "animation-timeline",
            "animation-timing-function",
            "",
            "",
            "",
            "",
            "",
            "",
          ]
        },
        /* visual */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "visualGroup",
          "order": null,
          "properties": [
            "backdrop-filter",
            "backface-visibility",
            "background",
            "background-attachment",
            "background-blend-mode",
            "background-clip",
            "background-color",
            "background-image",
            "background-origin",
            "background-position",
            "background-position-x",
            "background-position-y",
            "background-repeat",
            "background-size",
            "box-decoration-break",                        
            "box-shadow",                        
            "clip-path",
            "color",
            "color-scheme",
            "column-count",
            "column-fill",
            "column-gap",
            "column-rule",
            "column-rule-color",
            "column-rule-style",
            "column-rule-width",
            "column-span",
            "column-width",
            "columns",
            "filter",
            "forced-color-adjust",
            "image-orientation",
            "image-rendering",
            "image-resolution",
            "isolation",
            "mask",
            "mask-border",
            "mask-border-mode",
            "mask-border-outset",
            "mask-border-repeat",
            "mask-border-slice",
            "mask-border-source",
            "mask-border-width",
            "mask-clip",
            "mask-composite",
            "mask-image",
            "mask-mode",
            "mask-origin",
            "mask-position",
            "mask-repeat",
            "mask-size",
            "mask-type",
            
            "",
            "",
            "mix-blend-mode",
            "z-index",
          ]
        },
        /* misc */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "miscGroup",
          "order": null,
          "properties": [
            "appearance",
            "caret",
            "contain",
            "contain-intrinsic-block-size",
            "contain-intrinsic-height",
            "contain-intrinsic-inline-size",
            "contain-intrinsic-size",
            "contain-intrinsic-width",
            "container",
            "container-name",
            "container-type",
            "content",
            "content-visibility",
            "counter-increment",
            "counter-reset",
            "counter-set",
            "cursor",
            "gap",
            "",
          ]
        }
      ],
      {
        "unspecified": "bottom",
        "emptyLineBeforeUnspecified": "always",
        "severity": "warning"
      }
		]
  }
}