/*
 * STYLELINT Configuration file for style formatting
 * Last update: 20230505
 * Merged data from https://github.com/mdn/browser-compat-data (https://unpkg.com/@mdn/browser-compat-data@5.2.55/data.json)
 * and https://www.w3.org/Style/CSS/all-properties.en.html
 */
module.exports = {
  extends: [
    "stylelint-config-standard",
    "stylelint-config-standard-scss"
  ],
  plugins: ["stylelint-order"],
	rules: {
    "declaration-empty-line-before": null,
		"order/order": [
			[
				"dollar-variables",
				"custom-properties",
				"at-rules",
				"declarations",
				{
					"type": "at-rule",
					"name": "supports"
				},
				{
					"type": "at-rule",
					"name": "media"
				},
				"rules"
			],
			{ "severity": "warning" }
		],
		"order/properties-order": [
      [
        /* position */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "positionGroup",
          "order": null,
          "properties": [
            "position",
            "top",
            "right",
            "bottom",
            "left",
            "inset",
            "inset-block",
            "inset-block-end",
            "inset-block-start",
            "inset-inline",
            "inset-inline-end",
            "inset-inline-start",
            "vertical-align"
          ]
        },
        /* display */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "displayGroup",
          "order": null,
          "properties": [
            "display",
            "flex",
            "flex-basis",
            "flex-direction",
            "flex-flow",
            "flex-grow",
            "flex-shrink",
            "flex-wrap",
            "float",
            "clear",
            "grid",
            "grid-area",
            "grid-auto-columns",
            "grid-auto-flow",
            "grid-auto-rows",
            "grid-column",
            "grid-column-end",
            "grid-column-start",
            "grid-row",
            "grid-row-end",
            "grid-row-start",
            "grid-template",
            "grid-template-areas",
            "grid-template-columns",
            "grid-template-rows",
            "justify-content",
            "justify-items",
            "justify-self",
            "justify-tracks",
            "masonry-auto-flow",
            "order", // flex/grid
            "place-content",
            "place-items",
            "place-self",
            "row-gap",
            "ruby-align",
            "ruby-position",
            "visibility"            
          ]
        },
        /* box */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "boxGroup",
          "order": null,
          "properties": [
            "box-sizing",
            "width",
            "height",
            "max-height",
            "max-width",
            "min-height",
            "min-width",
            "max-block-size",
            "min-block-size",
            "max-inline-size",
            "min-inline-size",
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "margin-block",
            "margin-block-end",
            "margin-block-start",
            "margin-inline",
            "margin-inline-end",
            "margin-inline-start",
            "margin-trim",
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
            "padding-block",
            "padding-block-end",
            "padding-block-start",
            "padding-inline",
            "padding-inline-end",
            "padding-inline-start",
            "border",
            "border-top",
            "border-right",
            "border-bottom",
            "border-left",
            "border-color",
            "border-style",
            "border-width",
            "border-spacing",
            "border-top-color",
            "border-top-style",
            "border-top-width",
            "border-right-color",
            "border-right-style",
            "border-right-width",
            "border-bottom-color",
            "border-bottom-style",
            "border-bottom-width",
            "border-left-color",
            "border-left-style",
            "border-left-width",
            "border-radius",
            "border-start-end-radius",
            "border-start-start-radius",
            "border-end-end-radius",
            "border-end-start-radius",
            "border-top-left-radius",
            "border-top-right-radius",
            "border-bottom-right-radius",
            "border-bottom-left-radius",
            "border-block",
            "border-block-color",
            "border-block-end",
            "border-block-end-color",
            "border-block-end-style",
            "border-block-end-width",
            "border-block-start",
            "border-block-start-color",
            "border-block-start-style",
            "border-block-start-width",
            "border-block-style",
            "border-block-width",
            "border-collapse",
            "border-image",
            "border-image-outset",
            "border-image-repeat",
            "border-image-slice",
            "border-image-source",
            "border-image-width",
            "border-inline",
            "border-inline-color",
            "border-inline-end",
            "border-inline-end-color",
            "border-inline-end-style",
            "border-inline-end-width",
            "border-inline-start",
            "border-inline-start-color",
            "border-inline-start-style",
            "border-inline-start-width",
            "border-inline-style",
            "border-inline-width",
            "aspect-ratio",
            "align-content",
            "align-items",
            "align-self",
            "align-tracks",
            "break-after",
            "break-before",
            "break-inside",
            "inline-size",
            "outline",
            "outline-color",
            "outline-offset",
            "outline-style",
            "outline-width",
            "overflow",
            "overflow-anchor",
            "overflow-block",
            "overflow-clip-box",
            "overflow-clip-box-block",
            "overflow-clip-margin",
            "overflow-inline",
            "overflow-wrap",
            "overflow-x",
            "overflow-y",
            "overscroll-behavior",
            "overscroll-behavior-block",
            "overscroll-behavior-inline",
            "overscroll-behavior-x",
            "overscroll-behavior-y",                  
            "resize",
            "scroll-behavior",
            "scroll-margin",
            "scroll-margin-block",
            "scroll-margin-block-end",
            "scroll-margin-block-start",
            "scroll-margin-bottom",
            "scroll-margin-inline",
            "scroll-margin-inline-end",
            "scroll-margin-inline-start",
            "scroll-margin-left",
            "scroll-margin-right",
            "scroll-margin-top",
            "scroll-padding",
            "scroll-padding-block",
            "scroll-padding-block-end",
            "scroll-padding-block-start",
            "scroll-padding-bottom",
            "scroll-padding-inline",
            "scroll-padding-inline-end",
            "scroll-padding-inline-start",
            "scroll-padding-left",
            "scroll-padding-right",
            "scroll-padding-top",
            "scroll-snap-align",
            "scroll-snap-stop",
            "scroll-snap-type",
            "scrollbar-3dlight-color",
            "scrollbar-arrow-color",
            "scrollbar-base-color",
            "scrollbar-color",
            "scrollbar-darkshadow-color",
            "scrollbar-face-color",
            "scrollbar-gutter",
            "scrollbar-highlight-color",
            "scrollbar-shadow-color",
            "scrollbar-width"
          ]
        },
        /* table */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "tableGroup",
          "order": null,
          "properties": [
            "caption-side",
            "empty-cells",
            "table-layout"
          ]
        },
        /* typography */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "typographyGroup",
          "order": null,
          "properties": [
            "all",
            "direction",
            "unicode-bidi",
            "font",
            "font-family",
            "font-size",
            "font-size-adjust",
            "font-weight",
            "font-style",
            "font-smooth",
            "font-stretch",
            "font-feature-settings",
            "font-kerning",
            "font-language-override",
            "font-optical-sizing",
            "font-palette",
            "font-synthesis",
            "font-synthesis-small-caps",
            "font-synthesis-style",
            "font-synthesis-weight",
            "font-variant",
            "font-variant-alternates",
            "font-variant-caps",
            "font-variant-east-asian",
            "font-variant-emoji",
            "font-variant-ligatures",
            "font-variant-numeric",
            "font-variant-position",
            "hanging-punctuation",
            "hyphenate-character",
            "hyphenate-limit-chars",
            "hyphens",
            "initial-letter",
            "initial-letter-align",
            "letter-spacing",
            "line-breack",
            "-webkit-line-clamp", // normaly better using line-clamp to avoid issues 
            "line-clamp",
            "line-grid",
            "line-height",
            "line-height-step",
            "math-depth",
            "math-shift",
            "math-style",
            "quotes",
            "text-align",
            "text-align-last",
            "text-combine-upright",
            "text-decoration",
            "text-decoration-color",
            "text-decoration-line",
            "text-decoration-skip",
            "text-decoration-skip-ink",
            "text-decoration-style",
            "text-decoration-thickness",
            "text-emphasis",
            "text-emphasis-color",
            "text-emphasis-position",
            "text-emphasis-style",
            "text-indent",
            "text-justify",
            "text-orientation",
            "text-overflow",
            "text-rendering",
            "text-shadow",
            "text-size-adjust",
            "text-transform",
            "text-underline-offset",
            "text-underline-position",
            "word-break",
            "word-spacing",
            "user-select",
            "white-space",
            "widows",
            "orphans",
            "writing-mode"
          ]
        },
        /* forms */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "miscGroup",
          "order": null,
          "properties": [
            "accent-color"
          ]
        },
        /* animation */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "animationGroup",
          "order": null,
          "properties": [
            "animation",
            "animation-composition",
            "animation-delay",
            "animation-direction",
            "animation-duration",
            "animation-fill-mode",
            "animation-iteration-count",
            "animation-name",
            "animation-play-state",
            "animation-range",
            "animation-range-end",
            "animation-range-start",
            "animation-timeline",
            "animation-timing-function",
            "offset",
            "offset-anchor",
            "offset-distance",
            "offset-path",
            "offset-position",
            "offset-rotate",
            "rotate",
            "scale",
            "scroll-timeline",
            "scroll-timeline-attachment",
            "scroll-timeline-axis",
            "scroll-timeline-name",
            "transform",
            "transform-box",
            "transform-origin",
            "transform-style",
            "transition",
            "transition-delay",
            "transition-duration",
            "transition-property",
            "transition-timing-function",                        
            "translate",
            "view-transition-name"
          ]
        },
        /* visual */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "visualGroup",
          "order": null,
          "properties": [
            "color",
            "color-scheme",
            "forced-color-adjust",
            "-webkit-text-fill-color",
            "-webkit-text-stroke",
            "-webkit-text-stroke-color",
            "-webkit-text-stroke-width",            
            "background",
            "background-attachment",
            "background-blend-mode",
            "background-clip",
            "background-color",
            "background-image",
            "background-origin",
            "background-position",
            "background-position-x",
            "background-position-y",
            "background-repeat",
            "background-size",
            "opacity",
            "box-decoration-break",
            "box-shadow",
            "object-fit",
            "object-position",
            "object-view-box",
            "image-orientation",
            "image-rendering",
            "image-resolution",
            "clip-path",
            "filter",
            "backdrop-filter",
            "backface-visibility",
            "list-style",
            "list-style-image",
            "list-style-position",
            "list-style-type",
            "column-count",
            "column-fill",
            "column-gap",
            "column-rule",
            "column-rule-color",
            "column-rule-style",
            "column-rule-width",
            "column-span",
            "column-width",
            "columns",
            "isolation",
            "mask",
            "mask-border",
            "mask-border-mode",
            "mask-border-outset",
            "mask-border-repeat",
            "mask-border-slice",
            "mask-border-source",
            "mask-border-width",
            "mask-clip",
            "mask-composite",
            "mask-image",
            "mask-mode",
            "mask-origin",
            "mask-position",
            "mask-repeat",
            "mask-size",
            "mask-type",
            "mix-blend-mode",
            "perspective",
            "perspective-origin",
            "zoom",
            "z-index",
          ]
        },
        /* device */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "deviceGroup",
          "order": null,
          "properties": [
            "print-color-adjust"
          ]
        },
        /* touchescreen */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "deviceGroup",
          "order": null,
          "properties": [
            "touch-action"
          ]
        },
        /* misc */
        {
          "emptyLineBefore": "always",
          "noEmptyLineBetween": true,
          "groupName": "miscGroup",
          "order": null,
          "properties": [
            "appearance",
            "caret",
            "contain",
            "contain-intrinsic-block-size",
            "contain-intrinsic-height",
            "contain-intrinsic-inline-size",
            "contain-intrinsic-size",
            "contain-intrinsic-width",
            "container",
            "container-name",
            "container-type",
            "content",
            "content-visibility",
            "counter-increment",
            "counter-reset",
            "counter-set",
            "cursor",
            "pointer-events",
            "gap",
            "page",
            "page-break-after",
            "page-break-before",
            "page-break-inside",
            "paint-order",
            "shape-image-threshold",
            "shape-margin",
            "shape-outside",
            "tab-size"
          ]
        }
      ],
      {
        "unspecified": "bottom",
        "emptyLineBeforeUnspecified": "always",
        "severity": "warning"
      }
		]
  }
}